USE [master];
GO

-- Step 1: Backup the existing database if it exists
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'ArgaamScreener_DEV')
BEGIN
    DECLARE @BackupPath NVARCHAR(500) = 'C:\Backup\ArgaamScreener_DEV_' + 
                                        FORMAT(GETDATE(), 'yyyyMMdd_HHmmss') + '.bak';
    
    PRINT 'Backing up existing database...';
    BACKUP DATABASE [ArgaamScreener_DEV] TO DISK = @BackupPath WITH FORMAT, INIT;
    
    PRINT 'Backup complete. Deleting existing database...';
    ALTER DATABASE [ArgaamScreener_DEV] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [ArgaamScreener_DEV];
END;
GO

-- Step 2: Create the new database
PRINT 'Creating new database...';
CREATE DATABASE [ArgaamScreener_DEV]
CONTAINMENT = NONE
WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF;
GO

PRINT 'Database created successfully.';

ALTER DATABASE [ArgaamScreener_DEV] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ArgaamScreener_DEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ARITHABORT OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET RECOVERY FULL 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET  MULTI_USER 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ArgaamScreener_DEV] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ArgaamScreener_DEV] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ArgaamScreener_DEV] SET QUERY_STORE = OFF
GO
