USE [ArgaamScreener_DEV];
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO