name: Run Flyway Migrations

on:
  push:
    branches:
      - dev

jobs:
  flyway-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Set up Flyway
        run: |
          wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.10.0/flyway-commandline-7.10.0-linux-x64.tar.gz
          tar -xvzf flyway-commandline-7.10.0-linux-x64.tar.gz
          sudo mv flyway-7.10.0 /opt/flyway
          echo "export PATH=\$PATH:/opt/flyway" >> ~/.bashrc
          echo "export PATH=\$PATH:/opt/flyway" >> ~/.profile
          source ~/.bashrc # Make sure the new PATH is loaded
          export PATH=$PATH:/opt/flyway

      - name: Run Flyway Migrations
        run: |
          /opt/flyway/flyway -url=$DB_URL -user=$DB_USER -password=$DB_PASSWORD -locations=filesystem:./migrations migrate
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
