name: Run Flyway Migrations

on:
  push:
    branches:
      - dev

jobs:
  flyway-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Download and Install Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz | tar xz
          sudo mv flyway-*/ /opt/flyway
          echo "export PATH=\$PATH:/opt/flyway" >> ~/.bashrc
          echo "export PATH=\$PATH:/opt/flyway" >> ~/.profile
          export PATH=$PATH:/opt/flyway

      - name: Run Flyway Migrations
        run: |
          /opt/flyway/flyway -url=${{ secrets.DB_URL }} -user=${{ secrets.DB_USER }} -password=${{ secrets.DB_PASSWORD }} -locations=filesystem:./migrations migrate
